= {product} - Historias de Usuario
Universidad Cat칩lica Boliviana. <joseph.colbert@ucb.edu.bo>
1.0.0
:product: Bot de Cine
 
## 100- Compra de tickets, pipocas y golosinas
Autor: Joseph Colbert
 
Fecha: 03-06-2022
 
Prioridad: Alta
 
## Descripci칩n
 
Un usuario debe solicitar la compra de tickets, pipocas o golosinas por medio de la aplicaci칩n, para esto debe acceder a telegram y establecer una comunicaci칩n con el bot.
De esta manera el bot se encargar치 de desplegar diferentes opciones de compra, tanto para el ticket de cine como para las golosinas y pipocas. Con relaci칩n a la compra de golosinas el bot estar치 encargado de almacenar la informaci칩n del pedido el cual el trabajador correspondiente podr치 tener acceso a ella y preparar
el pedido con anticipaci칩n. En cuanto a la compra de tickets de cine, el bot deber치 pedir todos los datos requeridos como ser el n칰mero de personas,la pel칤cula deseada, los asientos requeridos, y como tal m칠todo de pago. Teniendo en cuenta toda la informaci칩n requerida por el bot, 칠ste deber치 almacenar y brindar la informaci칩n necesaria a quien corresponda.
 
## Diagrama
 
[plantuml, format="png", id="estados-solicitud"]
....
@startuml
 
actor usuario
usuario -> Bot : Solicitar compra de tickets, pipocas o golosinas
database baseDeDatos
Bot -> baseDeDatos: Solicitar informacion
baseDeDatos -> Bot: Brindar informacion
Bot -> usuario:
usuario -> Bot: Seleccionar requerimientos solicitados
Bot -> baseDeDatos: Almacenar informacion
Bot -> usuario: Solicitar informacion de la tarjeta
usuario -> Bot: Brindar informacion de la tarjeta
Bot -> baseDeDatos: Almacenar informacion de la tarjeta
Bot -> Banco:Realizar consuta
Banco -> Bot: Regresar aprobacion de transferencia
Bot -> baseDeDatos: Almacenar la compra
baseDeDatos -> Bot: Brindar informacion
Bot -> usuario: Brindar mensaje de compra exitosa
 
@enduml
....
 
## Escenarios
 
SOLICITADO: Cuando el usuario manda una solicitud de compra al Bot y dicho Bot no la rechaza.
SOLICITUD RECHAZADA: Solicitud rechazada por diferentes factores de informacion
SOLICITUD ACEPTADA: El bot acepta toda la informaci칩n para la compra y procede a almacenar dicha informaci칩n.
 
## Casos de Prueba
 
123.000.1 Validacion de informacion
Al momento de registrar los datos de la tarjeta del usuario, los siguientes datos son obligatorios :
Nombre del titular de la tarjeta, n칰mero de la tarjeta, emisor de la tarjeta(visa, mastercard,etc), fecha de caducidad
cvv(no recuerdo el nombre).
En caso que el usuario no ingrese uno de estos valores, la compra no deber칤a proceder
 
## Pasos:
 
1. Ingresar al bot via telegram y enviar el comando/start
    - Resultado esperado: el bot brinda una serie de opciones para poder seleccionarlas
2. El usuario selecciona la compra de tickets de cine
    - Resultado esperado: el bot brindara la lista de pel칤culas en cartelera
3. El usuario selecciona la pel칤cula deseada
    - Resultado esperado: el bot desplegar치 los horarios disponibles
4. El usuario seleccionara el horario requerido
    - Resultado esperado: el bot deber치 desplegar la opci칩n de la cantidad de tickets deseados.
5. El usuario ingresar치 la cantidad de tickets
    - Resultado esperado: el bot desplegar치 la opci칩n para seleccionar asientos.
6. El usuario seleccionar치 los asientos deseados.
    - Resultado esperado: el bot proceder치 a mostrar el m칠todo de pago
7. El usuario ingresa datos no v치lidos/emojis
    - Datos: Titular de la tarjeta: 'Juan Perez游때'
    - Resultado esperado: el bot le indicar치 que no puede colocar caracteres especiales.
8. El usuario coloca un espacio en blanco.
    - Datos: 'espacio en blanco'
    - Resultado esperado: el bot pide ingresar todos los datos de la tarjeta para poder validar la compra.
 

