= {product} - Histórias de Usuario
:product: Bot para un Cine

## Historias de Usuario.

## Introduccion 

El presente documento detalla toda la funcionalidad referente al Bot de cine, esto mediante diferentes historias de usaurio las cuales abarcaran las siguinetes funcionalidades: 

Cine:

* Cargar películas y horarios, con fotografías.

* Ver ocupación de una sala de cine.

* Controlar acceso al cine con tickets virtuales
* Ver pedidos para las próximas funciones.
* Entregar pedidos.

Cliente:

* Comprar tickets para las películas.
* Comprar golosinas y bebidas para las películas
* Recoger un pedido de golosinas.

### 100 Cargar Horarios y Películas
*Autor* : Marcelo Miranda

*Fecha* : 7/02/2022

*Prioridad* : ALTA

## Descripción
Como 'Empleado' del cine, debo realizar el cargado de las películas, para eso debo contar con un usuario para ingresar al sistema, para el cargado de las películas, debo ingresar la siguiente información:

 * Nombre de la película 
 * Horario para cada función 
 * Sala en la que se emitirá la película 
 * Género de la película
 * Fechas de las funciones
 * Fotografia de la película
 
Toda esta información se debe guardar en una BDD, El bot debe tomar en cuenta los siguientes aspectos:

 * La información del usuario sea correcto para ingresar al sistema.
 * Verificar si hay choque de horarios entre películas en alguna sala.
 * Mostrar una lista con las películas que se agregaron.

El diagrama de secuencias es el siguiente:

[plantuml, format="png",id= "ingresar-pelicula"]

....
@startuml
actor Empleado
Empleado -> Bot : Ingresar nueva película
Bot -> Empleado: Pedir Usuario
Empleado -> Bot : Ingresar datos
database Empleados
Bot --> Empleados : Verificar Datos de Usuario
Empleados --> Bot : Datos Verificados
Bot -> Empleado : Dar Respuesta
Empleado -> Bot : Ingresar Datos de la Película
database Películas
Bot --> Películas : Ingresa Datos
Películas --> Bot : Notificar el ingreso de datos
Bot -> Empleado : Datos Ingresados

@enduml
....

## Escenarios

 * El empleado ingresa de forma erronea sus datos de usuario.
 * El empleado no ingresa todos los datos de la película.
 * Choque de horarios entre dos películas en una misma sala.

## Casos de Prueba

### 100.1.1 Ingresar al sistema

Descripción: El empleado ingresa sus datos para poder ingresar al sistema.

 1. Ingresa al bot por medio de Telegram y coloca sus datos pero de forma erronea
  * Empleado: /Hola
  * Bot: Hola, ingrese su Usuario
  * Empleado: Juan12
  * Bot: Ingrese su contraseña
  * Empleado: 1548913
  * Bot: Usuario o Contraseña son incorrectos, vuelva a intentarlo
 
 2. El empleado se equivoca mas de 3 veces
  * Bot: Hola, ingrese su Usuario
  * Empleado: Juan12
  * Bot: Ingrese su contraseña
  * Empleado: Contraseña
  * Bot: Usuario o Contraseña son incorrectos, llego al número maximo de intentos, intentelo de nuevo dentro de 1h

 3. El empleado no ingresa algun dato
  * Empleado: /Hola
  * Bot: Hola, ingrese su Usuario
  * Empleado: 
  * Bot: Ingrese su Usuario, no debe dejar espacios vacios

 4. El empleado ingresa sus datos de forma correcta
  * Empleado: /Hola
  * Bot: Hola, ingrese su Usuario
  * Empleado: Juan12
  * Bot: Ingrese su contraseña
  * Empleado: Juan12
  * Bot: Datos correctos (Despliega el menu de Empleado)

### 100.1.2 Ingresar los datos de la película
Descripción: El empleado elige la opcion de "Cargar Película" para luego ingresar la información.

 1. El empleado elige la opción de "Cargar Película"
  * Bot: Elija una opción ingresando el número
   1 Cargar Película 2 Modificar .......... 10 Cerrar Sesión
  * Empleado: 1
  * Bot: Ingrese el nombre de la película

 2. El empleado no llena algun campo de la película
  * Bot: Ingrese el nombre de la película
  * Empleado: 
  * Bot: No se acepta campos vacios, vuelva a llenarlo por favor
 
 3. El empleado ingresa la información pero hay un choque de horarios
  * Bot: Ingrese los horarios (Despliega menu con horarios)
  * Empleado: (Elije los horarios)
  * Bot: Elija las salas (Despliega menu con numero de salas)
  * Empleado: (Elije las salas)
  * Bot: Hay un choque de horarios, horario 16:00 sala 1, vuelva a elegir los horarios o la sala

 4. El empleado ingresa toda la información de forma correcta de la película
  * Bot: Ingrese el nombre de la película
  * Empleado: Batman
  * Bot: Ingrese el género (Despliega menu con géneros)
  * Empleado: (Elige el género)
  * Bot: Ingrese los horarios (Despliega menu con horarios)
  * Empleado: (Elije los horarios)
  * Bot: Elija las salas (Despliega menu con numero de salas)
  * Empleado: (Elije las salas)
  * Bot: Ingrese la fotografia
  * Empleado: (Ingresa la fotografia)
  * Bot: Ingreso de datos exitosos
  
### 102 Entrega de tickets y productos

*Autor*: Marcelo Ugarte Heredia

*Fecha*: 03/07/2022

*Prioridad*: MUY ALTA

## Descripcion 

El bot generara un codigo de reserva con la reserva de las entradas en los puestos que el usaurio haya elegido 
una vez echo esto el usuario debera dirigirse a un empleado en caja y de esa manera mostrar el codigo de reserva 
para que este pueda generar sus entradas directamente por lo cual el empleado del cine debera pedir la siguiente 
informacion:

	* Codigo de reserva 

	* Nombre completo 

Una vez echo esto el empleado generara las entradas correspondientes de la misma manera si es que el usuario hace
la compra de algun combo de comida el empleado debera ver la hora a la que el usaurio reservo el combo para que 
este pueda ir preparando ya la comida y a la hora de que el usaurio pase a recoger la comida el empelado debera 
pedir la siguiente informacion:

	* Codigo de reserva 
	* Nombre completo 
Toda esta informacion es guardada en un BDD

El diagrama de secuencias para la presente historia es el siguiente:

[plantuml, target=hitoria - usuario, format=png]
....
@startuml
actor usuario
actor empleado
usuario -> empleado : Entregar codigo de reserva
empleado -> BOT : Ingresar datos de la reserva 
database BDD
BOT -> BDD : Validar datos de reserva
BDD -> BOT : Mandar respuesta de reserva
BOT -> empleado:  Notificar sobre el estado de la reserva 
empleado -> usuario : Entrega tickets y/o comidas 
@enduml
.... 

## Escenarios
1. Reserva de tickets aprobada
2. Reserva de tickets denegada 
3. Reserva de comida aprobada 
4. Reerva de comida denegada
5. Validacion de datos del usuario por el empleado

## Casos de prueba 
Descripcion: Al momento de recoger los tickets o la comida el empleado debera pedir algunos datos para poder hacer
la entrega de los mismos y asi poder reconocer a cada usuario.
En caso de que alguno de los datos sea erroneo o no correspondan con la reserva estos no deberan desplegar ninguna 
infromacion ni tampoco podra entregar ninguno de los dos objetos.

Pasos: 

	1. Ingresar al BOT via telegram y enviar el /start
		- Resultado esperado: El bot despleagara un menu con varias opciones para el empleado
	2. El `empleado` envia el comando /reserva de tickets 
		- Datos: Codigo de reserva del usuario 
		- Resultado esperado: El BOT pregunta por el codigo de reserva
	3. El empleado pone un espacio en blanco
		- Datos: Espacio en blanco 
		- Reultado esperado: El bot pedira nuevamente el codigo de reserva 
	4. El `empleado` generalas entradas o comida respectiva del usuario 
		- Resultado esperado: El bot marcara como "entregado" el pedido del usuario
  

