= {product} - Historias de Usuario
:product: Bot para un Cine

## Historias de Usuario.

## Introducci칩n 

El presente documento detalla toda la funcionalidad referente al Bot de cine, esto mediante diferentes historias de usuario las cuales abarcaran las siguientes funcionalidades: 

Cine:

* Cargar pel칤culas y horarios, con fotograf칤as.

* Ver ocupaci칩n de una sala de cine.

* Controlar acceso al cine con tickets virtuales
* Ver pedidos para las pr칩ximas funciones.
* Entregar pedidos.

Cliente:

* Comprar tickets para las pel칤culas.
* Comprar golosinas y bebidas para las pel칤culas
* Recoger un pedido de golosinas.

### 100 Cargar Horarios y Pel칤culas
*Autor* : Marcelo Miranda

*Fecha* : 7/02/2022

*Prioridad* : ALTA

## Descripci칩n
Como 'Empleado' del cine, debo realizar el cargado de las pel칤culas, para eso debo contar con un usuario para ingresar al sistema, para el cargado de las pel칤culas, debo ingresar la siguiente informaci칩n:

 * Nombre de la pel칤cula 
 * Horario para cada funci칩n 
 * Sala en la que se emitir치 la pel칤cula 
 * G칠nero de la pel칤cula
 * Fechas de las funciones
 * Fotograf칤a de la pel칤cula
 
Toda esta informaci칩n se debe guardar en una BDD, El Bot debe tomar en cuenta los siguientes aspectos:

 * La informaci칩n del usuario sea correcto para ingresar al sistema.
 * Verificar si hay choque de horarios entre pel칤culas en alguna sala.
 * Mostrar una lista con las pel칤culas que se agregaron.

El diagrama de secuencias es el siguiente:

[plantuml, format="png",id= "ingresar-pelicula"]

....
@startuml
actor Empleado
Empleado -> Bot : Ingresar nueva pel칤cula
Bot -> Empleado: Pedir Usuario
Empleado -> Bot : Ingresar datos
database Empleados
Bot --> Empleados : Verificar Datos de Usuario
Empleados --> Bot : Datos Verificados
Bot -> Empleado : Dar Respuesta
Empleado -> Bot : Ingresar Datos de la Pel칤cula
database Pel칤culas
Bot --> Pel칤culas : Ingresa Datos
Pel칤culas --> Bot : Notificar el ingreso de datos
Bot -> Empleado : Datos Ingresados

@enduml
....

## Escenarios

 * El empleado ingresa de forma err칩nea sus datos de usuario.
 * El empleado no ingresa todos los datos de la pel칤cula.
 * Choque de horarios entre dos pel칤culas en una misma sala.

## Casos de Prueba

### 100.1.1 Ingresar al sistema

Descripci칩n: El empleado ingresa sus datos para poder ingresar al sistema.

 1. Ingresa al Bot por medio de Telegram y coloca sus datos, pero de forma err칩nea
  * Empleado: /Hola
  * Bot: Hola, ingrese su Usuario
  * Empleado: Juan12
  * Bot: Ingrese su contrase침a
  * Empleado: 1548913
  * Bot: Usuario o Contrase침a son incorrectos, vuelva a intentarlo
 
 2. El empleado se equivoca m치s de 3 veces
  * Bot: Hola, ingrese su Usuario
  * Empleado: Juan12
  * Bot: Ingrese su contrase침a
  * Empleado: Contrase침a
  * Bot: Usuario o Contrase침a son incorrectos, llego al n칰mero m치ximo de intentos, int칠ntelo de nuevo dentro de 1h

 3. El empleado no ingresa alg칰n dato
  * Empleado: /Hola
  * Bot: Hola, ingrese su Usuario
  * Empleado: 
  * Bot: Ingrese su Usuario, no debe dejar espacios vac칤os

 4. El empleado ingresa sus datos de forma correcta
  * Empleado: /Hola
  * Bot: Hola, ingrese su Usuario
  * Empleado: Juan12
  * Bot: Ingrese su contrase침a
  * Empleado: Juan12
  * Bot: Datos correctos (Despliega el men칰 de Empleado)

### 100.1.2 Ingresar los datos de la pel칤cula
Descripci칩n: El empleado elige la opci칩n de "Cargar Pel칤cula" para luego ingresar la informaci칩n.

 1. El empleado elige la opci칩n de "Cargar Pel칤cula"
  * Bot: Elija una opci칩n ingresando el n칰mero
   1 Cargar Pel칤cula 2 Modificar .......... 10 Cerrar Sesi칩n
  * Empleado: 1
  * Bot: Ingrese el nombre de la pel칤cula

 2. El empleado no llena alg칰n campo de la pel칤cula
  * Bot: Ingrese el nombre de la pel칤cula
  * Empleado: 
  * Bot: No se acepta campos vac칤os, vuelva a llenarlo por favor
 
 3. El empleado ingresa la informaci칩n, pero hay un choque de horarios
  * Bot: Ingrese los horarios (Despliega men칰 con horarios)
  * Empleado: (Elije los horarios)
  * Bot: Elija las salas (Despliega men칰 con n칰mero de salas)
  * Empleado: (Elije las salas)
  * Bot: Hay un choque de horarios, horario 16:00 sala 1, vuelva a elegir los horarios o la sala

 4. El empleado ingresa toda la informaci칩n de forma correcta de la pel칤cula
  * Bot: Ingrese el nombre de la pel칤cula
  * Empleado: Batman
  * Bot: Ingrese el g칠nero (Despliega men칰 con g칠neros)
  * Empleado: (Elige el g칠nero)
  * Bot: Ingrese los horarios (Despliega men칰 con horarios)
  * Empleado: (Elije los horarios)
  * Bot: Elija las salas (Despliega men칰 con n칰mero de salas)
  * Empleado: (Elije las salas)
  * Bot: Ingrese la fotograf칤a
  * Empleado: (Ingresa la fotograf칤a)
  * Bot: Ingreso de datos exitosos

 
## 101- Compra de tickets, pipocas y golosinas
Autor: Joseph Colbert
 
Fecha: 03-09-2022
 
Prioridad: Muy Alta
 
## Descripci칩n
 
Como cliente del cine debo solicitar la compra de tickets, pipocas o golosinas por medio de la aplicaci칩n, para esto debe acceder a telegram y establecer una comunicaci칩n con el bot. De esta manera el bot se encargar치 de desplegar diferentes opciones de compra, tanto para el ticket de cine como para las golosinas y pipocas. Con relaci칩n a la compra de golosinas el bot estar치 encargado de almacenar la informaci칩n del pedido donde el trabajador correspondiente podr치 tener acceso a ella y preparar el pedido con anticipaci칩n. 
En cuanto a la compra de tickets de cine, 
El bot deber치 pedir todos los datos requeridos para la compra del ticket como ser:

      *  El n칰mero de personas
      *  La pel칤cula deseada, 
      *  Los asientos requeridos,
      *  Como tal m칠todo de pago.

El bot deber치 pedir todos los datos requeridos para la compra de las golosinas y pipocas como ser:

        * Tama침o de pipocas 
        * Tama침o de refresco
        * Tipo de golosina
        * Como tal el metodo de pago

Teniendo en cuenta toda la informaci칩n requerida por el bot, 칠ste deber치 almacenar y brindar la informaci칩n necesaria a quien corresponda.


 
El diagrama de secuencias para la presente historia es el siguiente:
 
[plantuml, format="png", id="estados-solicitud"]
....
@startuml
 
actor usuario
usuario -> Bot : Solicitar compra de tickets, pipocas o golosinas
database baseDeDatos
Bot -> baseDeDatos: Solicitar informacion
baseDeDatos -> Bot: Brindar informacion
Bot -> usuario:
usuario -> Bot: Seleccionar requerimientos solicitados
Bot -> baseDeDatos: Almacenar informacion
Bot -> usuario: Solicitar informacion de la tarjeta
usuario -> Bot: Brindar informacion de la tarjeta
Bot -> baseDeDatos: Almacenar informacion de la tarjeta
Bot -> Banco:Realizar consuta
Banco -> Bot: Regresar aprobacion de transferencia
Bot -> baseDeDatos: Almacenar la compra
baseDeDatos -> Bot: Brindar informacion
Bot -> usuario: Brindar mensaje de compra exitosa
 
@enduml
....
 
## Escenarios
 
* El cliente solicita la compra de ticket para una sala llena.
* El cliente introduce mal sus datos referentes a la compra de tickets, golosinas o pipocas.
* El cliente solicita la compra de paquetes de golosinas o pipocas agotados.
* El cliente selecciona asientos ya ocupados.
 
## Casos de Prueba
 
101.1 Solicitud de compra de tickets:

Se prueba la respuesta del Bot cuando un cliente requiere la compra de un ticket para una sala llena.

Pasos:

1. Ingresar al bot via telegram y enviar el comando/start
    - Resultado esperado: el bot brinda una serie de opciones para poder seleccionarlas
2. El usuario selecciona la compra de tickets de cine
    - Resultado esperado: el bot brindara la lista de pel칤culas en cartelera
3. El usuario selecciona la pel칤cula deseada
    - Resultado esperado: el bot desplegar치 los horarios disponibles
4. El usuario seleccionara el horario requerido para una sala llena
    - Resultado esperado: el bot desplegara el siguiente mensaje "Sala llena, porfavor seleccione otro horario"


101.2 Validacion de informacion:

Al momento de registrar los datos de la tarjeta del usuario, los siguientes datos son obligatorios :
Nombre del titular de la tarjeta, n칰mero de la tarjeta, emisor de la tarjeta(visa, mastercard,etc), fecha de caducidad
cvv.
En caso que el usuario no ingrese uno de estos valores, la compra no deber칤a proceder

Pasos:
 
1. Ingresar al bot via telegram y enviar el comando/start
    - Resultado esperado: el bot brinda una serie de opciones para poder seleccionarlas
2. El usuario selecciona la compra de tickets de cine
    - Resultado esperado: el bot brindara la lista de pel칤culas en cartelera
3. El usuario selecciona la pel칤cula deseada
    - Resultado esperado: el bot desplegar치 los horarios disponibles
4. El usuario seleccionara el horario requerido
    - Resultado esperado: el bot deber치 desplegar la opci칩n de la cantidad de tickets deseados.
5. El usuario ingresar치 la cantidad de tickets
    - Resultado esperado: el bot desplegar치 la opci칩n para seleccionar asientos.
6. El usuario seleccionar치 los asientos deseados.
    - Resultado esperado: el bot proceder치 a mostrar el m칠todo de pago
7. El usuario ingresa datos no v치lidos/emojis
    - Datos: Titular de la tarjeta: 'Juan Perez游때'
    - Resultado esperado: el bot le indicar치 que no puede colocar caracteres especiales con el siguiente mensaje " Porfavor introduzca la informacion sin caracteres especiales".
8. El usuario coloca un espacio en blanco.
    - Datos: 'espacio en blanco'
    - Resultado esperado: el bot pide ingresar todos los datos de la tarjeta con el siguientre mensaje "Porfavor rellene todos los campos para poder validar la compra". 
 

101.3 Solicitud de compra de pipocas o golosinas

Se prueba la respuesta del Bot cuando un cliente requiere la compra de pipocas o golosinas para un paquete ya agotado.

Pasos:

1. Ingresar al bot via telegram y enviar el comando/start
    - Resultado esperado: el bot brinda una serie de opciones para poder seleccionarlas
2. El usuario selecciona la compra de pipocas o golosinas
    - Resultado esperado: el bot brindara la lista de paquetes disponibles
3. El usuario selecciona un paquete agotado
    - Resultado esperado: el bot desplegar치 el siguiente mensaje "Paquete agotado, seleccione uno diferente"

101.4 Asignacion de asientos:

Se prueba la respuesta del Bot cuando un cliente realiza la compra de un ticket, en el cual selecciona un asiento ocupado.

Pasos:

1. Ingresar al bot via telegram y enviar el comando/start
    - Resultado esperado: el bot brinda una serie de opciones para poder seleccionarlas
2. El usuario selecciona la compra de tickets de cine
    - Resultado esperado: el bot brindara la lista de pel칤culas en cartelera
3. El usuario selecciona la pel칤cula deseada
    - Resultado esperado: el bot desplegar치 los horarios disponibles
4. El usuario seleccionara el horario requerido para una sala llena
    - Resultado esperado: el bot deber치 desplegar la opci칩n de la cantidad de tickets deseados.
5. El usuario ingresar치 la cantidad de tickets
    - Resultado esperado: el bot desplegar치 la opci칩n para seleccionar asientos.
6. El usuario seleccionar치 los asientos ocupados.
    - Resultado esperado: el bot desplegar치 el siguiente mensaje "Asientos ocupados, porfavor seleccione diferentes asientos"

  
### 102 Entrega de tickets y productos

*Autor*: Marcelo Ugarte Heredia

*Fecha*: 03/07/2022

*Prioridad*: ALTA

## Descripcion 

Un empleado solicitar치 al cliente el c칩digo de compra, Se proceder치 a la verificaci칩n correspondiente mediante el bot para el cual pedir치 los siguientes datos:
 
    * C칩digo de reserva
 
    * Nombre del cliente
 
Una vez realizada la petici칩n, el empleado generar치 las entradas correspondientes, de la misma manera se proceder치 a la entrega de alg칰n tipo de un combo de golosinas o pipocas.
 
El diagrama de secuencias para la presente historia es el siguiente:
 
[plantuml, target=hitoria - usuario, format=png]
....
@startuml
actor usuario
actor empleado
usuario -> empleado : Entregar codigo de reserva
empleado -> BOT : Ingresar datos de la reserva
database BDD
BOT -> BDD : Validar datos de reserva
BDD -> BOT : Mandar respuesta de reserva
BOT -> empleado:  Notificar sobre el estado de la reserva
empleado -> usuario : Entrega tickets y/o comidas
@enduml
....
 
## Escenarios
 
- El cliente brindar치 informaci칩n previamente registrada.
- El cliente brindar치 informaci칩n err칩nea o inexistente.
 
 
## Casos de prueba
 
102.1. Validaci칩n de codigo de compra ya utilizado
 
Descripci칩n: El empleado har치 la b칰squeda del c칩digo de compras mediante el cual desplegar치 la informaci칩n en caso de que est칠 vigente o no haya sido utilizado previamente.
 
Pasos:
 
    1. Ingresar al BOT via telegram y enviar /start
        - Resultado esperado: El bot desplegar치 un men칰 con varias opciones para el empleado
    2. El empleado selecciona el comando /c칩digo de compra
        - Datos: Codigo de compra del usuario ya utilizado
        - Resultado esperado: El BOT desplegar치 el siguiente mensaje "C칩digo ya utilizado"
   
102.2. Validaci칩n de c칩digo de compra inexistente
 
Descripci칩n: El empleado har치 la b칰squeda del c칩digo de compras mediante el cual si este no existe se desplegar치 una alerta.
Pasos:
 
    1. Ingresar al BOT via telegram y enviar /start
        - Resultado esperado: El bot desplegar치 un men칰 con varias opciones para el empleado
   2. El empleado selecciona el comando /c칩digo de compra
        - Datos: Codigo de compra del usuario ya utilizado
        - Resultado esperado: El BOT desplegara el siguiente mensaje "C칩digo de compra inexistente"

